### ISSUE TITLE
Removing items from existing carousel tiles does not work

### ISSUE THREAD

**Issue by fredvd** [collective/collective.cover#475] opened 2015-01-28 14:44 UTC
In a site upgraded to the latest c.cover master version we can no longer remove carousel items from the carousel compose screen.  Clicking the (x) marker on an item works, but saving the form blinks the following message with "wrong contained type" for a second and then closes without removing the item. The added items are Link CT objects.  
 
![wrong_contained_type](https://cloud.githubusercontent.com/assets/394784/5939383/81f2eefc-a703-11e4-95c6-50ac0cee64c4.gif)

Removing the carousel tile as a whole and re-adding the same Link CT objects solves the problem, then I can remove the same items.

With the updates to the list'y and carousel tiles in the recent months and the double migration, does anyone have an idea what's going on here? @frapell @hvelarde @mauritsvanrees ? 

I've added pdb to the UUIDSFieldDataConverter(BaseDataConverter) class in carousel.py to verify what's going in and out to the form and the data looks sane to mee, all dict()'s. The uuids storage on an existing and migrated carousel tile and the newly created carousel tile also look the same, dicts with the same structure afaics. "Wrong contained type" seems to come from z3c.form (it's also presented as a validation error) when I search. And unfortunately there's no exception/backtrace to look into.

My workaround is to rebuild the carousel tiles in the content db, but when upgrading c.cover to the next released version other users might be affected by this as well.

**Comment by fredvd** [comment] 2015-01-28 17:22
After more debugging and testing, my workaround to remove the carousel tile and repopulate does not work, the problem pops up on new carousel tiles as well.

The problem seems to be that under some conditions after modifying values in the compose edit for a carousel tile, the browser sends back a json string which is unicode in the request and cannot be parsed by the server. Note the `{u"{u` at the beginning of the value catched in the UUIDSFieldDataConverter ToFieldValue method in carousel.py : 

` {u"{u'b3eb8414716a478f8a288e993325ff8e': {u'custom_description': u'slecht', u'custom_title': u'Slecht !', u'order': u'0', u'custom_url': u'http://xxxxx/afbeeldingen/Tickred.png/view'}, u'a51e533497e149938b93984763a57f61': {u'custom_description': u'De waterkwaliteit in Vlaanderen verbetert, maar paradoxaal genoeg zorgt dat ervoor dat onze waterlopen gevoeliger zijn en er makkelijker vissterfte optreedt. Een snelle melding van vissen in nood is de eerste en belangrijkste stap.\\r\\n', u'custom_title': u'Vissterfte? Melden!', u'order': u'1', u'custom_url': u'xxxxxxxxx'}}": {u'custom_description': u'', u'custom_title': u'', u'order': u'0', u'custom_url': u''}}`

If you try to parse this with json.loads it complains about single quotes and the u's. 

We (@fredvd @mauritsvanrees ) haven't found yet what triggers this on the browser side.

**Comment by hvelarde** [comment] 2015-01-29 23:26
have you checked if this could be related with #467 issue?

**Comment by fredvd** [comment] 2015-01-30 07:58
As far as we can see the uuids data stored on the tile is a dict() and sane. The error is a validation error, but the tile edit overlay closes anyway 0.5-1 second after pressing save. 

At some point the data from a fileld is coming back or is represented in a dictionairy enclosed in a unicode string which is just weird, but the fields are sent in a normal form post.

**Comment by hvelarde** [comment] 2015-01-30 11:30
are you able to remove the items in some other way?

**Comment by fredvd** [comment] 2015-01-30 14:03
The only trick/work around so far is removing them all at the same time, then the valdiation error is not triggerd on the widget because there's nothing left :-)

Fred

**Comment by runyaga** [comment] 2015-01-31 01:59
@fredvd what version of cover were you using previously?  I can double check if this is happening on a customers site (which has not been reported or surfaced in our sentry reports) and if we can reproduce - we will begin work on it.

**Comment by fredvd** [comment] 2015-01-31 09:49
@runyaga, we've sticking to master as close as possible, making and using internal releases every 2-4 weeks depending on what has been committed and tests run. This issue is with current master and p.conttenttypes 1.1b3 on Plone 4.3.4. We've been using this throughout 2014. 

When debugging this last week I already realised that allthough c.cover is dexterit the test suite is fully running on AT content tested in c.cover. We could add a test suite with p.a.contenttypes as well, that could improve testing.don't know actually if the Plone 5 tests are run at the moment for every commit as well.

**Comment by frapell** [comment] 2015-02-08 17:21
@fredvd I have just created a whole new site with latest master ( 6692b522ba97292d09c0d308917084cd9b94bb94 ) and I cannot reproduce what you mention.

**Comment by djowett** [comment] 2015-03-27 12:43
Hi, 
   maybe this is something to do with UserDict?  I say this because I've been debugging tests on the new carousel tile & found an error in test_internal_structure which could only be solved by changing 

     self.assertTrue(isinstance(uuids, dict))

to
     self.assertIsInstance(uuids, (dict, UserDict))

The passing build is here: https://travis-ci.org/collective/covertile.cycle2/builds/56084985

I can't figure out where UserDict comes from - but do note that it is NOT a subclass of dict

**Comment by hvelarde** [comment] 2015-03-31 19:33
@djowett check if that is related with #467

**Comment by fredvd** [comment] 2015-04-01 09:28
PersistentMapping is implemented as a subclass of UserDict, so that's where it's coming frrom @djowett

**Comment by djowett** [comment] 2015-04-01 09:55
Ok, thanks. I had assumed that Travis was pulling in master of collective.cover (where PersistentMapping is gone), when I guess it's just getting the latest release (1.0a10).

**Comment by fredvd** [comment] 2015-04-01 12:52
@djowett, @hvlarde I can no longer reproduce this issue with current master (April 1st 2015) on an in production content database, items are now removable. The fixes for the related carousel issues seem to have solved this one as well.

**Comment by hvelarde** [comment] 2015-04-01 13:57
ok, I'm closing this issue then

**Closed by hvelarde** 2015-04-01 13:57 UTC
