### ISSUE TITLE
carousel tile stores portal_url in all dropped carousel items when you modify one of the items in the carousel dialog

### ISSUE THREAD

**Issue by fredvd** [collective/collective.cover#476] opened 2015-02-03 15:31 UTC
When you add items to a carousel bry dropping them on the carousel the links and al data that the carousel shows is pulled from the referenced/dropped object by storing the objects UUID

As soon as you go into the edit dialog of the carousel you will see title, description, and url of each item to modify/override. However: as soon as you do this for any single item, all 'references' in the carousel are cut and the data is copied to the carousel: including the full path to the item including the website address. 

This breaks setups where a different domain/backend is used for editing (cms.website.com) or when you set up a new site on a staging domain and afterwards switch the site to another domain to go 'live'.

**Comment by frapell** [comment] 2015-02-08 17:31
@fredvd I have just tested this and cannot reproduce. This is the internal structure just after dropping 2 objects to a carousel tile using latest master (6692b522ba97292d09c0d308917084cd9b94bb94)

```
{'autoplay': True,
 'count': None,
 'css_class': None,
 'date': None,
 'description': None,
 'image': None,
 'more_link': None,
 'more_link_text': None,
 'tile_title': None,
 'title': None,
 'uuids': {'6df3ab2a7f484cc499fa60cc8bdf50c7': {u'order': u'0'},
           'eaa9dd40b86443f1ae98b8bd8b4b437a': {u'order': u'1'}}}
```

And this is right after manually editing title, description and URL for them
```
{'autoplay': True,
 'count': None,
 'css_class': None,
 'date': None,
 'description': None,
 'image': None,
 'more_link': None,
 'more_link_text': None,
 'tile_title': None,
 'title': None,
 'uuids': {u'6df3ab2a7f484cc499fa60cc8bdf50c7': {u'custom_description': u'This is a description',
                                                 u'custom_title': u'Custom title 1',
                                                 u'custom_url': u'http://www.google.com/custom_1',
                                                 u'order': u'0'},
           u'eaa9dd40b86443f1ae98b8bd8b4b437a': {u'custom_description': u'This is another description',
                                                 u'custom_title': u'Custom title 2',
                                                 u'custom_url': u'http://www.google.com/custom_1',
                                                 u'order': u'1'}}}
```

**Comment by fredvd** [comment] 2015-02-08 18:32
@frapell And what is the internal structure if you drop 2-3 objects onto an empty carousel, you edit only the title of the first object and then save?

**Comment by frapell** [comment] 2015-02-08 21:58
@fredvd Ahh, I see now what you mean. This seems to have been broken after commits d1091d70d5c62eec4b1a337f9b69591e6c63f03c and 3c4473bd5afa40b58f8fc0f7542cd3c1ff5b1016

If you checkout the revision prior to that, you'll see that the field is not auto populated, and it works fine

**Comment by hvelarde** [comment] 2015-02-09 10:47
@rodfersou check this out, please.

**Comment by rodfersou** [comment] 2015-02-09 23:49
I see.. the problem is that we need a new check if the item was modified in extract method.
I'll try to fix it.

**Comment by rodfersou** [comment] 2015-02-25 20:36
This issue was closed in pull request https://github.com/collective/collective.cover/pull/479

**Comment by fredvd** [comment] 2015-04-01 12:40
@rodfersou: The test for changes in custom attributes is not working correctly yet on unicode/utf8 items. 
If I add a newsitem to a carousel and then go into the compoe edit overlay to change the carousel title (and not any of the items), The newsitem with utf8 in for this example the description will still get set as a custom field in tie ITileData dictionairy. 

After first drop of the item:
ipdb> from plone.tiles.interfaces import ITileDataManager ; print ITileDataManager(context.get_tile(u'ad5449954e5c49b4')).get()20a461 
{'count': None, 'description': None, 'title': None, 'css_class': None, 'image': None, 'more_link_text': None, 'more_link': None, 'uuids': {'42a60df3bf2c417ab3389c939894e992': {u'order': u'0'}}, 'date': None, 'autoplay': True, 'tile_title': u'Mijn Carousel'}
ipdb> c
--Return--

After changing the Carousel tile title:

ipdb> from plone.tiles.interfaces import ITileDataManager ; print ITileDataManager(context.get_tile(u'ad5449954e5c49b4')).get()20a461 
{'count': None, 'description': None, 'title': None, 'css_class': None, 'image': None, 'more_link_text': None, 'more_link': None, 'uuids': {u'42a60df3bf2c417ab3389c939894e992': {u'custom_description': u'Experten hebben in opdracht van de Vlaamse Milieumaatschappij zes megatrends bestudeerd die belangrijk zijn voor het milieu in Vlaanderen. Ze gingen na hoe die trends ontstaan, hoe ze zich in Vlaanderen manifesteren en hoe ze via grote maatschappelijke systemen ons milieu be\xefnvloeden.', u'order': u'0'}}, 'date': None, 'autoplay': True, 'tile_title': u'Change Carousel Title'}


Also for an existing carousel tile I got these warnings occasionally when running in the foreground (not when adding the utf8 content item above). When I clear the tile and add items again this is not happening:

/var/zope/.buildoutcache/eggs/collective.cover-1.0a11_zest_20150331-py2.7.egg/collective/cover/widgets/textlinessortable.py:146: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if custom_description != obj.Description():

**Comment by rodfersou** [comment] 2015-04-22 11:19
This pull request https://github.com/collective/collective.cover/pull/511 closes this issue

**Closed by rodfersou** 2015-04-22 11:19 UTC
Labels: bug
