### ISSUE TITLE
KeyError: 'column-size' when adding a cover page

### ISSUE THREAD

**Issue by tisto** [collective/collective.cover#844] opened 2018-10-18 10:18 UTC
- Plone 4.3.3
- collective.cover 1.0a11 - 1.7b3 (ZODB has c.cover 1.0a11, I tried to upgrade with gs step, no difference)

Seems like this is a known issue:

https://github.com/plonegovbr/brasil.gov.tiles/issues/132

When I try to add a cover page I get the following traceback:

> 2018-10-18 12:10:32 ERROR Zope.SiteErrorLog 1539857432.40.893470974184 http://localhost:8080/Plone/++add++collective.cover.content
> Traceback (innermost last):
>   Module ZPublisher.Publish, line 138, in publish
>   Module ZPublisher.mapply, line 77, in mapply
>   Module ZPublisher.Publish, line 48, in call_object
>   Module plone.z3cform.layout, line 66, in __call__
>   Module plone.z3cform.layout, line 60, in update
>   Module z3c.form.form, line 263, in render
>   Module z3c.form.form, line 158, in render
>   Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
>   Module zope.pagetemplate.pagetemplate, line 132, in pt_render
>   Module zope.pagetemplate.pagetemplate, line 240, in __call__
>   Module zope.tal.talinterpreter, line 271, in __call__
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 888, in do_useMacro
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 518, in do_optTag
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 954, in do_defineSlot
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 518, in do_optTag
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 858, in do_defineMacro
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 518, in do_optTag
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 522, in do_optTag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 858, in do_defineMacro
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 518, in do_optTag
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 821, in do_loop_tal
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 518, in do_optTag
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 954, in do_defineSlot
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 518, in do_optTag
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 858, in do_defineMacro
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 518, in do_optTag
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 531, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
>   Module zope.tales.tales, line 696, in evaluate
>    - URL: /Users/timo/workspace/***-intranet/eggs/plone.app.z3cform-0.7.6-py2.7.egg/plone/app/z3cform/templates/macros.pt
>    - Line 97, Column 46
>    - Expression: <PathExpr standard:u'widget/@@ploneform-render-widget'>
>    - Names:
>       {'args': (),
>        'context': <PloneSite at /Plone>,
>        'default': <object object at 0x10931fc40>,
>        'loop': {},
>        'nothing': None,
>        'options': {},
>        'repeat': {},
>        'request': <HTTPRequest, URL=http://localhost:8080/Plone/++add++collective.cover.content>,
>        'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x10fe658d0>,
>        'view': <plone.dexterity.browser.add.DefaultAddForm object at 0x11382e350>,
>        'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0x1132321d0>}
>   Module zope.tales.expressions, line 217, in __call__
>   Module Products.PageTemplates.Expressions, line 155, in _eval
>   Module Products.PageTemplates.Expressions, line 117, in render
>   Module Products.Five.browser.metaconfigure, line 479, in __call__
>   Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
>   Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
>   Module zope.pagetemplate.pagetemplate, line 132, in pt_render
>   Module zope.pagetemplate.pagetemplate, line 240, in __call__
>   Module zope.tal.talinterpreter, line 271, in __call__
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 858, in do_defineMacro
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 954, in do_defineSlot
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 531, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
>   Module zope.tales.tales, line 696, in evaluate
>    - URL: /Users/timo/workspace/***-intranet/eggs/plone.app.z3cform-0.7.6-py2.7.egg/plone/app/z3cform/templates/widget.pt
>    - Line 37, Column 4
>    - Expression: <PathExpr standard:u'widget/render'>
>    - Names:
>       {'args': (),
>        'context': <SelectPreviewWidget 'form.widgets.template_layout'>,
>        'default': <object object at 0x10931fc40>,
>        'loop': {},
>        'nothing': None,
>        'options': {},
>        'repeat': {},
>        'request': <HTTPRequest, URL=http://localhost:8080/Plone/++add++collective.cover.content>,
>        'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x1132b4750>,
>        'view': <Products.Five.metaclass.RenderWidget object at 0x1139d1110>,
>        'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0x113482210>}
>   Module zope.tales.expressions, line 217, in __call__
>   Module zope.tales.expressions, line 211, in _eval
>   Module collective.cover.widgets.selectpreview, line 54, in render
>   Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
>   Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
>   Module zope.pagetemplate.pagetemplate, line 132, in pt_render
>   Module zope.pagetemplate.pagetemplate, line 240, in __call__
>   Module zope.tal.talinterpreter, line 271, in __call__
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 531, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
>   Module zope.tales.tales, line 696, in evaluate
>    - URL: /Users/timo/workspace/***-intranet/eggs/collective.cover-1.7b3-py2.7.egg/collective/cover/widgets/selectpreview_input.pt
>    - Line 7, Column 0
>    - Expression: <PathExpr standard:u'view/js'>
>    - Names:
>       {'args': (<SelectPreviewWidget 'form.widgets.template_layout'>,),
>        'context': <PloneSite at /Plone>,
>        'default': <object object at 0x10931fc40>,
>        'loop': {},
>        'nothing': None,
>        'options': {},
>        'repeat': {},
>        'request': <HTTPRequest, URL=http://localhost:8080/Plone/++add++collective.cover.content>,
>        'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x1133aa550>,
>        'view': <SelectPreviewWidget 'form.widgets.template_layout'>,
>        'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0x1139d1350>}
>   Module zope.tales.expressions, line 217, in __call__
>   Module zope.tales.expressions, line 211, in _eval
>   Module collective.cover.widgets.selectpreview, line 45, in js
>   Module collective.cover.widgets.selectpreview, line 73, in simplify_layout
>   Module collective.cover.widgets.selectpreview, line 64, in simplify_layout
> KeyError: 'column-size'
> 2018-10-18 12:12:24 ERROR Zope.SiteErrorLog 1539857544.390.118148242031 http://localhost:8080/Plone/++add++collective.cover.content
> Traceback (innermost last):
>   Module ZPublisher.Publish, line 138, in publish
>   Module ZPublisher.mapply, line 77, in mapply
>   Module ZPublisher.Publish, line 48, in call_object
>   Module plone.z3cform.layout, line 66, in __call__
>   Module plone.z3cform.layout, line 60, in update
>   Module z3c.form.form, line 263, in render
>   Module z3c.form.form, line 158, in render
>   Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
>   Module zope.pagetemplate.pagetemplate, line 132, in pt_render
>   Module zope.pagetemplate.pagetemplate, line 240, in __call__
>   Module zope.tal.talinterpreter, line 271, in __call__
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 888, in do_useMacro
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 518, in do_optTag
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 954, in do_defineSlot
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 518, in do_optTag
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 858, in do_defineMacro
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 518, in do_optTag
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 522, in do_optTag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 858, in do_defineMacro
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 518, in do_optTag
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 821, in do_loop_tal
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 518, in do_optTag
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 954, in do_defineSlot
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 518, in do_optTag
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 858, in do_defineMacro
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 533, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 518, in do_optTag
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 531, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
>   Module zope.tales.tales, line 696, in evaluate
>    - URL: /Users/timo/workspace/***-intranet/eggs/plone.app.z3cform-0.7.6-py2.7.egg/plone/app/z3cform/templates/macros.pt
>    - Line 97, Column 46
>    - Expression: <PathExpr standard:u'widget/@@ploneform-render-widget'>
>    - Names:
>       {'args': (),
>        'context': <PloneSite at /Plone>,
>        'default': <object object at 0x10931fc40>,
>        'loop': {},
>        'nothing': None,
>        'options': {},
>        'repeat': {},
>        'request': <HTTPRequest, URL=http://localhost:8080/Plone/++add++collective.cover.content>,
>        'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x10fe658d0>,
>        'view': <plone.dexterity.browser.add.DefaultAddForm object at 0x1139e1c10>,
>        'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0x1136ef910>}
>   Module zope.tales.expressions, line 217, in __call__
>   Module Products.PageTemplates.Expressions, line 155, in _eval
>   Module Products.PageTemplates.Expressions, line 117, in render
>   Module Products.Five.browser.metaconfigure, line 479, in __call__
>   Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
>   Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
>   Module zope.pagetemplate.pagetemplate, line 132, in pt_render
>   Module zope.pagetemplate.pagetemplate, line 240, in __call__
>   Module zope.tal.talinterpreter, line 271, in __call__
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 858, in do_defineMacro
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 954, in do_defineSlot
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 531, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
>   Module zope.tales.tales, line 696, in evaluate
>    - URL: /Users/timo/workspace/***-intranet/eggs/plone.app.z3cform-0.7.6-py2.7.egg/plone/app/z3cform/templates/widget.pt
>    - Line 37, Column 4
>    - Expression: <PathExpr standard:u'widget/render'>
>    - Names:
>       {'args': (),
>        'context': <SelectPreviewWidget 'form.widgets.template_layout'>,
>        'default': <object object at 0x10931fc40>,
>        'loop': {},
>        'nothing': None,
>        'options': {},
>        'repeat': {},
>        'request': <HTTPRequest, URL=http://localhost:8080/Plone/++add++collective.cover.content>,
>        'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x1132b4750>,
>        'view': <Products.Five.metaclass.RenderWidget object at 0x113725f10>,
>        'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0x113725d50>}
>   Module zope.tales.expressions, line 217, in __call__
>   Module zope.tales.expressions, line 211, in _eval
>   Module collective.cover.widgets.selectpreview, line 54, in render
>   Module zope.browserpage.viewpagetemplatefile, line 83, in __call__
>   Module zope.browserpage.viewpagetemplatefile, line 51, in __call__
>   Module zope.pagetemplate.pagetemplate, line 132, in pt_render
>   Module zope.pagetemplate.pagetemplate, line 240, in __call__
>   Module zope.tal.talinterpreter, line 271, in __call__
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 531, in do_optTag_tal
>   Module zope.tal.talinterpreter, line 513, in no_tag
>   Module zope.tal.talinterpreter, line 343, in interpret
>   Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
>   Module zope.tales.tales, line 696, in evaluate
>    - URL: /Users/timo/workspace/***-intranet/eggs/collective.cover-1.7b3-py2.7.egg/collective/cover/widgets/selectpreview_input.pt
>    - Line 7, Column 0
>    - Expression: <PathExpr standard:u'view/js'>
>    - Names:
>       {'args': (<SelectPreviewWidget 'form.widgets.template_layout'>,),
>        'context': <PloneSite at /Plone>,
>        'default': <object object at 0x10931fc40>,
>        'loop': {},
>        'nothing': None,
>        'options': {},
>        'repeat': {},
>        'request': <HTTPRequest, URL=http://localhost:8080/Plone/++add++collective.cover.content>,
>        'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x1133aa550>,
>        'view': <SelectPreviewWidget 'form.widgets.template_layout'>,
>        'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0x11374d8d0>}
>   Module zope.tales.expressions, line 217, in __call__
>   Module zope.tales.expressions, line 211, in _eval
>   Module collective.cover.widgets.selectpreview, line 45, in js
>   Module collective.cover.widgets.selectpreview, line 73, in simplify_layout
>   Module collective.cover.widgets.selectpreview, line 64, in simplify_layout
> KeyError: 'column-size'

**Comment by hvelarde** [comment] 2018-10-18 13:08
@tisto the issue you are referring happened only on tests for tiles depending on a customization, so it's not related. IIRC, there was an upgrade step that changed the layout structure (#513), did you ran that one?

@rodfersou can you give a hint here?

**Comment by rodfersou** [comment] 2018-10-18 14:41
Looks like the default layout is broken, is it possible to remove this setting by hand then you can create a new cover: https://github.com/collective/collective.cover/blob/1.0a11/src/collective/cover/profiles/default/registry.xml#L5-L18

Or maybe fix the current default layout by hand.  Also the mentioned upgrade step by @hvelarde should automatically fix the default layouts.

**Comment by hvelarde** [comment] 2018-10-18 15:53
@tisto you can always create a new cover with an empty layout and then edit it in the layout tab.

**Comment by idgserpro** [comment] 2018-10-18 17:38
>IIRC, there was an upgrade step that changed the layout structure (#513), did you ran that one?

@hvelarde  it is necessary to know if the first installation of cover was in version 1.0a11. #513 was already present in version 1.0a11. Then would not need to upgrade step.

@tisto ?

**Comment by rodfersou** [comment] 2019-02-19 16:26
@tisto the problem is related with custom layout into the project profile.

I'm closing this issue for now.

**Closed by rodfersou** 2019-02-19 16:26 UTC
