### ISSUE TITLE
Carousel 'Edit' option doesn't work

### ISSUE THREAD

**Issue by IolaneAndrade** [collective/collective.cover#846] opened 2018-11-01 14:50 UTC
I tried to edit the carousel tile, but some error occurred and the tile remained empty.
the followed steps were:
1. Inside the cover I accessed the compose;
2. I did access the "edit"  carousel option;
3. I selected some News to showing in carousel
4. I did save the process
5. nothing happend

When I access the cover' view, it show a message "tile saved", but nothing is showing

**Comment by hvelarde** [comment] 2018-11-01 21:36
what version of collective.cover are you using? are there any errors in the JavaScript console? note that this feature is fully tested:

https://github.com/collective/collective.cover/blob/master/src/collective/cover/tests/test_carousel_tile.robot#L113-L192

**Comment by IolaneAndrade** [comment] 2018-11-04 21:32
The versions used were:
 - Plone 4.3.18
 - cover 2.1b2

I saw that there were tests, however, I tried to execute the action and the carousel didn't display the links that I added in the edition
The javascript didn't return any error and at the end of the action the message "tile saved" was displayed

**Comment by hvelarde** [comment] 2018-11-05 22:38
does the news items have a lead image?

**Comment by IolaneAndrade** [comment] 2018-11-06 11:13
yes,
all the news have a lead image

**Comment by hvelarde** [comment] 2018-11-06 16:23
no traceback, no console logs… sorry, but it's difficult to help you without any hint of what could be failing.

**Comment by IolaneAndrade** [comment] 2018-11-06 17:06
When I try to edit the carrousel tile,
no error is displayed (nothing in traceback, in console logs), in fact a success message is displayed (tile saved) but the carousel tile remains empty.

Maybe if you try to add some news in an instance of plone 4.3.18, and then edit the carousel to receive this news, you can see clearly.

**Comment by IolaneAndrade** [comment] 2018-11-07 02:19
In my case, I have edited the title fields and the field where a LINK is referenced.

example: using drag-and-drop I added news 1 and news 2.
Next I tried to edit the carousel tile, excluding the news I added previously and referencing link news 3 and 4.

But the carousel saves the tile empty  

On second thought, maybe this is an action not allowed
[reference a new link in the carousel] 🤔 

P.S. I'm using Chrome:stable. I'll try using Firefox

**Comment by hvelarde** [comment] 2018-11-07 11:37
the problem is you're excluding the news items, that's why you see nothing after saving.

I don't understand your use case: what are you trying to do?

**Comment by IolaneAndrade** [comment] 2018-11-08 11:44
The purpose of the action would be to change the highlighted news using the carousel edit option.

I thought this could be done by editing the LINK field

**Comment by hvelarde** [comment] 2018-11-08 13:17
no, that's not the use case; if you need to change the main item on the carousel you can remove old items and to drop a new ones on it; you can also reorder the items on the carousel using the Edit option: you'll see a hand as mouse pointer to indicate that when you're over a item on the list.

I'm closing this as we agree there is no issue after all.

**Closed by hvelarde** 2018-11-08 13:17 UTC

**Comment by IolaneAndrade** [comment] 2018-11-08 13:21
But what is the purpose of the "link" field?
What should this field do?

**Comment by hvelarde** [comment] 2018-11-08 13:54
that's the destination of the link in the title; you can change it in case you want users be redirected somewhere else outside the site.
